name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  using: 'node16'
  main: 'main.js'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v3

      - name: Deploy to Web Server
        run: |
          aws configure
          aws s3 sync dist/ s3://your-bucket-name --delete
