name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Run Super-Linter
        uses: github/super-linter@v3

      - name: Deploy to Web Server
        run: |
          aws configure
          aws s3 sync dist/ s3://your-bucket-name --delete
